about:
  description: Nimbus Feature Manifest for Monitor Web
channels:
  - staging
  - production
features:
  rebrand-announcement:
    description: Rebranding announcement
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: false
    defaults:
      - channel: staging
        value: { "enabled": false }
      - channel: production
        value: { "enabled": false }

types:
  objects: {}
  enums: {}
